FORMAT: 1A
HOST: http://sportadvisor-lb-81878895.us-east-1.elb.amazonaws.com
# sportadvisor-api


## Accounts [/api/users]

### Sign up [POST /api/users/sign-up]

+ Request (application/json)
    
        {
            "email": "string", 
            "password": "string", 
            "name": "string",
            "EULA": true
        }

+ Response 200 (application/json)

        {
            "code":  200,
            "data": {
                "data": {
                    "token": "string",
                    "refreshToken": "string",
                    "expireAt": "2018-06-19T07:12:45.972+03:00[Europe/Moscow]"
                },
                "_links": null
            }
        }

+ Response 400 (application/json)

        {
            "code":  400,
            "errors": [
                {
                    "field": "string",
                    "msg": "string"
                }
            ]
        }

### Sign in [POST /api/users/sign-in]

+ Request (application/json)

        {
            "email": "string",
            "password": "string",
            "remember": true
        }

+ Response 200 (application/json)

        {
            "code":  200,
            "data": {
                "data": {
                    "token": "string",
                    "refreshToken": "string",
                    "expireAt": "2018-06-19T07:12:45.972+03:00[Europe/Moscow]"
                },
                "_links": null
            }
        }

+ Response 400 (application/json)

        {
            "code":  400
        }

### Change an account [PUT /api/users/{id}]

+ Parameters
    + id - user id

+ Request (application/json)

    + Headers
        Authorization: token

    + Body
        {
            "name": "string",
            "language": "string (is optional value)"
        }

+ Response (application/json)

    + Headers
        Location: locationUrl

    + Body
        {
            "code":  200
        }

+ Response 400 (application/json)

        {
            "code":  400,
            "errors": [
                {
                    "field": "string",
                    "msg": "string"
                }
            ]
        }


### Change an email [PUT /api/users/{id}/email]

+ Parameters
    + id - user id

+ Request (application/json)

    + Headers
        Authorization: token

    + Body
        {
            "email": "string",
            "redirectUrl": "string"
        }

+ Response 200 (application/json)

        {
            "code":  200
        }

+ Response 400 (application/json)

        {
            "code":  400,
            "errors": [
                {
                    "field": "string",
                    "msg": "string"
                }
            ]
        }

+ Response 401 (application/json)

        {
            "code": 401
        }

+ Response 403 (application/json)

        {
            "code": 403
        }

### Confirm an email [POST /api/users/email-confirm]

+ Request (application/json)

        {
            "token": "string"
        }

+ Response 200 (application/json)

        {
            "code":  200
        }

+ Response 400 (application/json)

        {
            "code":  400
        }

### Reset a password [POST /api/users/reset-password]

+ Body
    {
        "email": "string",
        "redirectUrl": "string"
    }

+ Response 200 (application/json)

        {
            "code":  200
        }

### Confirm a new password [POST /api/users/password-confirm]

+ Body
    {
       "token": "string",
       "password": "string"
    }

+ Response 200 (application/json)

        {
            "code":  200
        }

+ Response 400 (application/json)

        {
            "code":  400,
            "errors": [
                {
                    "field": "string",
                    "msg": "string"
                }
            ]
        }

### Get information about the authorized user [GET /api/users/me]

+ Request

    + Headers
        Authorization: token

+ Response 303

    + Headers
        Location: /api/users/{id}

+ Response 401 (application/json)

        {
            "code": 401
        }

### Get information about user [GET /api/users/{id}]

+ Parameters
    + id - user id

+ Request

    + Headers
        Authorization: token

+ Response 200 (application/json)

    {
        "code":200,
        "data": {
            "data": {
                "id": 1,
                "email": "email@email.emal",
                "name": "name",
                "language": "ru"
            },
            "_links": {
                "self": {
                    "href":"/api/users/1"
                }
            }
        }
    }

+ Response 401 (application/json)

        {
            "code": 401
        }

+ Response 403 (application/json)

        {
            "code": 403
        }

+ Response 404 (application/json)

        {
            "code": 404
        }

### Change a password [PUT /api/users/{id}/password]

+ Parameters
    + id - user id

+ Request

    + Headers
        Authorization: token

    + Body
        {
            "password": "string",
            "newPassword": "string"
        }

+ Response 200 (application/json)

        {
            "code":  200
        }

+ Response 400 (application/json)

        {
            "code":  400,
            "errors": [
                {
                    "field": "string",
                    "msg": "string"
                }
            ]
        }

+ Response 401 (application/json)

        {
            "code": 401
        }

+ Response 403 (application/json)

        {
            "code": 403
        }

### User logout [POST /api/users/logout]

+ Response 200 (application/json)

        {
            "code":  200
        }

+ Response 401 (application/json)

        {
            "code": 401
        }