version: 2
jobs:
  unit-test:
    docker:
      - image: som3t1me5/circleci-sbt:latest
    working_directory: ~/sport-advisor-api
    steps:
      - checkout
      - restore_cache:
          keys:
            - sportadvisor-api-{{ checksum "build.sbt" }}
      - run: sbt test
      - save_cache:
          key: sportadvisor-api-{{ checksum "build.sbt" }}
          paths:
            - ~/.sbt
            - ~/.ivy2/cache
            - ~/.m2
      - persist_to_workspace:
          root: /home/node/
          paths:
            - sport-advisor-api
  e2e-test:
    machine:
          image: circleci/classic:201711-01
          docker_layer_caching: true
    working_directory: ~/sport-advisor-api
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: mv /tmp/workspace/sport-advisor-api ~/
      - restore_cache:
          keys:
            - sportadvisor-api-{{ checksum "build.sbt" }}-e2e
      - run: sbt version # crutch for downloading sbt
      - run: sbt docker e2e:test
      - run: mkdir /home/circleci/docker-cache && docker save -o /home/circleci/docker-cache/build-image.tar io.sportadvisor/sportadvisor-core:latest
      - run: mv .circleci/deploy.sh /home/circleci/docker-cache/
      - save_cache:
                key: sportadvisor-api-{{ checksum "build.sbt" }}-e2e
                paths:
                  - ~/.sbt
                  - ~/.ivy2/cache
                  - ~/.m2
      - persist_to_workspace:
          root: /home/circleci/docker-cache/
          paths:
            - build-image.tar
            - deploy.sh
  push-and-deploy-docker:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: docker load < /tmp/workspace/docker-cache/build-image.tar
      - run: docker tag io.sportadvisor/sportadvisor-core:latest ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/sportadvisor:latest
      - run: sh /tmp/workspace/.circleci/deploy.sh

workflows:
   version: 2
   build-and-deploy:
    jobs:
      - unit-test
#          filters:
#            branches:
#              only:
#                - master
      - e2e-test:
#          filters:
#            branches:
#              only:
#                - master
          requires:
            - unit-test
      - push-and-deploy-docker:
#          filters:
#            branches:
#              only:
#                - master
          requires:
            - e2e-test