version: 2
jobs:
  build:
    docker:
      - image: som3t1me5/circleci-sbt:latest
    working_directory: ~/sport-advisor-api
    steps:
      - checkout
      - restore_cache:
          keys:
            - sportadvisor-api-{{ checksum "build.sbt" }}
      - run: sbt test
      - run: sbt assembly
      - save_cache:
          key: sportadvisor-api-{{ checksum "build.sbt" }}
          paths:
            - ~/.sbt
            - ~/.ivy2/cache
            - ~/.m2
      - persist_to_workspace:
          root: /home/node/sport-advisor-api/
          paths:
            - target/scala-2.12/sportadvisor-api.jar
            - Dockerfile
            - .circleci/deploy.sh

  deploy-docker:
    machine:
      image: circleci/classic:201711-01
      docker_layer_caching: true
    working_directory: ~/sport-advisor-api
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: cd /tmp/workspace && docker build -t ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/sportadvisor:latest .
      - run: sh /tmp/workspace/.circleci/deploy.sh

workflows:
   version: 2
   build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy-docker:
          filters:
            branches:
              only:
                - master
          requires:
            - build